//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R.GoogleOutlookSync.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("R.GoogleOutlookSync.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string AboutBox_btnClose_Text {
            get {
                return ResourceManager.GetString("AboutBox_btnClose_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string AboutBox_btnRegister_Text {
            get {
                return ResourceManager.GetString("AboutBox_btnRegister_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        internal static string AboutBox_lblCompanyName_Text {
            get {
                return ResourceManager.GetString("AboutBox_lblCompanyName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        internal static string AboutBox_lblProductName_Text {
            get {
                return ResourceManager.GetString("AboutBox_lblProductName_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string AboutBox_lblVersion_Text {
            get {
                return ResourceManager.GetString("AboutBox_lblVersion_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GooOut web site.
        /// </summary>
        internal static string AboutBox_lnkHelp_Text {
            get {
                return ResourceManager.GetString("AboutBox_lnkHelp_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Service.
        /// </summary>
        internal static string AboutBox_lnkTermsOfService_Text {
            get {
                return ResourceManager.GetString("AboutBox_lnkTermsOfService_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {0}.
        /// </summary>
        internal static string AboutBox_Text {
            get {
                return ResourceManager.GetString("AboutBox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AboutBox_txtDescription_Text {
            get {
                return ResourceManager.GetString("AboutBox_txtDescription_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Accounts {
            get {
                object obj = ResourceManager.GetObject("Accounts", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Advanced {
            get {
                object obj = ResourceManager.GetObject("Advanced", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization range.
        /// </summary>
        internal static string CalendarSyncSettings_groupBox1_Text {
            get {
                return ResourceManager.GetString("CalendarSyncSettings_groupBox1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar synchronize settings.
        /// </summary>
        internal static string CalendarSyncSettings_groupBox2_Text {
            get {
                return ResourceManager.GetString("CalendarSyncSettings_groupBox2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days &amp;after.
        /// </summary>
        internal static string CalendarSyncSettings_label1_Text {
            get {
                return ResourceManager.GetString("CalendarSyncSettings_label1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days &amp;after.
        /// </summary>
        internal static string CalendarSyncSettings_label2_Text {
            get {
                return ResourceManager.GetString("CalendarSyncSettings_label2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days &amp;before.
        /// </summary>
        internal static string CalendarSyncSettings_label3_Text {
            get {
                return ResourceManager.GetString("CalendarSyncSettings_label3_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CalendarSyncSettings.
        /// </summary>
        internal static string CalendarSyncSettings_Text {
            get {
                return ResourceManager.GetString("CalendarSyncSettings_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart of application as administrator is needed. Do you want to proceed?.
        /// </summary>
        internal static string Confirm_RestartAsAdminNeeded {
            get {
                return ResourceManager.GetString("Confirm_RestartAsAdminNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to send the error report?.
        /// </summary>
        internal static string Confirm_SendSessionLog {
            get {
                return ResourceManager.GetString("Confirm_SendSessionLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to interrupt synchronization?.
        /// </summary>
        internal static string Confirm_StopSyncronization {
            get {
                return ResourceManager.GetString("Confirm_StopSyncronization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Skip.
        /// </summary>
        internal static string ConflictResolverForm_button1_Text {
            get {
                return ResourceManager.GetString("ConflictResolverForm_button1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ConflictResolverForm_cancel_Text {
            get {
                return ResourceManager.GetString("ConflictResolverForm_cancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep &amp;Google Entry.
        /// </summary>
        internal static string ConflictResolverForm_keepGoogle_Text {
            get {
                return ResourceManager.GetString("ConflictResolverForm_keepGoogle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep &amp;Outlook Entry.
        /// </summary>
        internal static string ConflictResolverForm_keepOutlook_Text {
            get {
                return ResourceManager.GetString("ConflictResolverForm_keepOutlook_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message.
        /// </summary>
        internal static string ConflictResolverForm_messagelabel_Text {
            get {
                return ResourceManager.GetString("ConflictResolverForm_messagelabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confict detected!.
        /// </summary>
        internal static string ConflictResolverForm_Text {
            get {
                return ResourceManager.GetString("ConflictResolverForm_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Duplicates Utility.
        /// </summary>
        internal static string DeleteDuplicatesForm_Text {
            get {
                return ResourceManager.GetString("DeleteDuplicatesForm_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another instance of {0} is already running..
        /// </summary>
        internal static string Error_AnotherInstanceIsRunning {
            get {
                return ResourceManager.GetString("Error_AnotherInstanceIsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t set autostart for GooOut.
        /// </summary>
        internal static string Error_AutostartSetFailure {
            get {
                return ResourceManager.GetString("Error_AutostartSetFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to Google, please check for available internet connection and proxy settings if applicable..
        /// </summary>
        internal static string Error_ConnectionFailure {
            get {
                return ResourceManager.GetString("Error_ConnectionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The schedule of event is not set. Current operation is impossible without having schedule set.
        /// </summary>
        internal static string Error_EventScheduleIsNotSet {
            get {
                return ResourceManager.GetString("Error_EventScheduleIsNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to Google. Internal exception contains last error reported during attempt to connect to Google.
        /// </summary>
        internal static string Error_GoogleConnectionFailure {
            get {
                return ResourceManager.GetString("Error_GoogleConnectionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item provided is neither Google nor Outlook one.
        /// </summary>
        internal static string Error_InvalidItem {
            get {
                return ResourceManager.GetString("Error_InvalidItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The action on the item failed:.
        /// </summary>
        internal static string Error_ItemSynchronizationFailure {
            get {
                return ResourceManager.GetString("Error_ItemSynchronizationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log could not be sent. Check connection and try again.
        /// </summary>
        internal static string Error_LogSendingFailure {
            get {
                return ResourceManager.GetString("Error_LogSendingFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no components to synchronize specified.
        ///Please select at least one of following:
        ///- Contacts
        ///- Calendar.
        /// </summary>
        internal static string Error_NoDataToSyncronizeSpecified {
            get {
                return ResourceManager.GetString("Error_NoDataToSyncronizeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your computer was not rebooted after GooOut installation. You must reboot computer before using GooOut. Do you want to reboot now?.
        /// </summary>
        internal static string Error_NotRebootedAfterInstallation {
            get {
                return ResourceManager.GetString("Error_NotRebootedAfterInstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to Outlook. Internal exception contains last error reported during attempt to connect to Outlook.
        /// </summary>
        internal static string Error_OutlookConnectionFailure {
            get {
                return ResourceManager.GetString("Error_OutlookConnectionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The profile &apos;{0}&apos; is not configured. Please close GooOut, finish profile configuration in Outlook and restart GooOut.
        /// </summary>
        internal static string Error_ProfileNotConfigured {
            get {
                return ResourceManager.GetString("Error_ProfileNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The serial key is invalid. Please verify the key and try again.
        /// </summary>
        internal static string Error_RegistrationFailure {
            get {
                return ResourceManager.GetString("Error_RegistrationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The interval for yearly recurrence pattern is not supported by this version of Outlook. This item won&apos;t be synchronized.
        /// </summary>
        internal static string Error_WrongYearlyInterval {
            get {
                return ResourceManager.GetString("Error_WrongYearlyInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Sync on.
        /// </summary>
        internal static string LogForm_lastSynclabel_Text {
            get {
                return ResourceManager.GetString("LogForm_lastSynclabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Details &amp;&amp; Log.
        /// </summary>
        internal static string LogForm_loggroupbox_Text {
            get {
                return ResourceManager.GetString("LogForm_loggroupbox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GooOut - Synchronization log.
        /// </summary>
        internal static string LogForm_Text {
            get {
                return ResourceManager.GetString("LogForm_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log was sent successfully.
        /// </summary>
        internal static string Notification_LogSent {
            get {
                return ResourceManager.GetString("Notification_LogSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync complete.
        /// </summary>
        internal static string Notification_SyncComplete {
            get {
                return ResourceManager.GetString("Notification_SyncComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync failed.
        /// </summary>
        internal static string Notification_SyncFailed {
            get {
                return ResourceManager.GetString("Notification_SyncFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update is failed.
        /// </summary>
        internal static string Notification_UpdateFailure {
            get {
                return ResourceManager.GetString("Notification_UpdateFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application is updated. Restart is needed.
        /// </summary>
        internal static string Notification_UpdateRestartNeeded {
            get {
                return ResourceManager.GetString("Notification_UpdateRestartNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application is updated successfully.
        /// </summary>
        internal static string Notification_UpdateSuccess {
            get {
                return ResourceManager.GetString("Notification_UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application is up to date.
        /// </summary>
        internal static string Notification_UpdateUpToDate {
            get {
                return ResourceManager.GetString("Notification_UpdateUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Proxies {
            get {
                object obj = ResourceManager.GetObject("Proxies", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap QuestionMarkIcon {
            get {
                object obj = ResourceManager.GetObject("QuestionMarkIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string RegisterForm_btnCancel_Text1 {
            get {
                return ResourceManager.GetString("RegisterForm_btnCancel_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;OK.
        /// </summary>
        internal static string RegisterForm_btnOk_Text1 {
            get {
                return ResourceManager.GetString("RegisterForm_btnOk_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get registration number.
        /// </summary>
        internal static string RegisterForm_lnkGetRegNumber_Text {
            get {
                return ResourceManager.GetString("RegisterForm_lnkGetRegNumber_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter registration number.
        /// </summary>
        internal static string RegisterForm_Text {
            get {
                return ResourceManager.GetString("RegisterForm_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered registration number will be applied after application restart.
        /// </summary>
        internal static string RegistrationSettings_RegistrationNotificationText {
            get {
                return ResourceManager.GetString("RegistrationSettings_RegistrationNotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A262-B752-GOOO-2552-1460-0010-0G.
        /// </summary>
        internal static string RegistrationSettings_RegistrationNumber {
            get {
                return ResourceManager.GetString("RegistrationSettings_RegistrationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Sync in.
        /// </summary>
        internal static string SettingForm_nextSyncLabel_Text {
            get {
                return ResourceManager.GetString("SettingForm_nextSyncLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A&amp;uthorization.
        /// </summary>
        internal static string SettingsForm_Authorization_Text {
            get {
                return ResourceManager.GetString("SettingsForm_Authorization_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync C&amp;alendar.
        /// </summary>
        internal static string SettingsForm_btSyncCalendar_Text {
            get {
                return ResourceManager.GetString("SettingsForm_btSyncCalendar_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync &amp;Contacts.
        /// </summary>
        internal static string SettingsForm_btSyncContacts_Text {
            get {
                return ResourceManager.GetString("SettingsForm_btSyncContacts_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use custom HTTP  proxy.
        /// </summary>
        internal static string SettingsForm_customproxy_Text {
            get {
                return ResourceManager.GetString("SettingsForm_customproxy_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Options.
        /// </summary>
        internal static string SettingsForm_groupBox2_Text {
            get {
                return ResourceManager.GetString("SettingsForm_groupBox2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy.
        /// </summary>
        internal static string SettingsForm_groupBox3_Text {
            get {
                return ResourceManager.GetString("SettingsForm_groupBox3_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Account.
        /// </summary>
        internal static string SettingsForm_groupBox4_Text {
            get {
                return ResourceManager.GetString("SettingsForm_groupBox4_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync frequency.
        /// </summary>
        internal static string SettingsForm_grpAutoSync_Text {
            get {
                return ResourceManager.GetString("SettingsForm_grpAutoSync_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Hide.
        /// </summary>
        internal static string SettingsForm_HideButton_Text {
            get {
                return ResourceManager.GetString("SettingsForm_HideButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy now.
        /// </summary>
        internal static string SettingsForm_InkBuynow_Text {
            get {
                return ResourceManager.GetString("SettingsForm_InkBuynow_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string SettingsForm_InkHelp_Text {
            get {
                return ResourceManager.GetString("SettingsForm_InkHelp_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync &amp;Interval:.
        /// </summary>
        internal static string SettingsForm_Label1_Text {
            get {
                return ResourceManager.GetString("SettingsForm_Label1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;User:.
        /// </summary>
        internal static string SettingsForm_Label2_Text {
            get {
                return ResourceManager.GetString("SettingsForm_Label2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Password:.
        /// </summary>
        internal static string SettingsForm_Label3_Text {
            get {
                return ResourceManager.GetString("SettingsForm_Label3_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mins.
        /// </summary>
        internal static string SettingsForm_Label4_Text {
            get {
                return ResourceManager.GetString("SettingsForm_Label4_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Outlook Profile:.
        /// </summary>
        internal static string SettingsForm_Label5_Text {
            get {
                return ResourceManager.GetString("SettingsForm_Label5_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;User:.
        /// </summary>
        internal static string SettingsForm_Label6_Text {
            get {
                return ResourceManager.GetString("SettingsForm_Label6_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Password:.
        /// </summary>
        internal static string SettingsForm_Label7_Text {
            get {
                return ResourceManager.GetString("SettingsForm_Label7_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Address:.
        /// </summary>
        internal static string SettingsForm_Label8_Text {
            get {
                return ResourceManager.GetString("SettingsForm_Label8_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P&amp;ort:.
        /// </summary>
        internal static string SettingsForm_Label9_Text {
            get {
                return ResourceManager.GetString("SettingsForm_Label9_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string SettingsForm_lblLanguage_Text {
            get {
                return ResourceManager.GetString("SettingsForm_lblLanguage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language will be changed on next application start.
        /// </summary>
        internal static string SettingsForm_lblLanguageChangeNotification_Text {
            get {
                return ResourceManager.GetString("SettingsForm_lblLanguageChangeNotification_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Auto sync.
        /// </summary>
        internal static string SettingsForm_mniAutoSync_Text {
            get {
                return ResourceManager.GetString("SettingsForm_mniAutoSync_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show &amp;log.
        /// </summary>
        internal static string SettingsForm_mniLog_Text {
            get {
                return ResourceManager.GetString("SettingsForm_mniLog_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter &amp;registration key.
        /// </summary>
        internal static string SettingsForm_mniRegister_Text {
            get {
                return ResourceManager.GetString("SettingsForm_mniRegister_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show s&amp;ettings.
        /// </summary>
        internal static string SettingsForm_mniSettings_Text {
            get {
                return ResourceManager.GetString("SettingsForm_mniSettings_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&amp;top sync.
        /// </summary>
        internal static string SettingsForm_mniStopSync_Text {
            get {
                return ResourceManager.GetString("SettingsForm_mniStopSync_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Sync.
        /// </summary>
        internal static string SettingsForm_mniSync_Text {
            get {
                return ResourceManager.GetString("SettingsForm_mniSync_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GooOut Multisynchronizer.
        /// </summary>
        internal static string SettingsForm_notifyIcon_Text {
            get {
                return ResourceManager.GetString("SettingsForm_notifyIcon_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re&amp;port Sync Result in System Tray.
        /// </summary>
        internal static string SettingsForm_reportSyncResultCheckBox_Text {
            get {
                return ResourceManager.GetString("SettingsForm_reportSyncResultCheckBox_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Reset Matches.
        /// </summary>
        internal static string SettingsForm_resetMatchesLinkLabel_text {
            get {
                return ResourceManager.GetString("SettingsForm_resetMatchesLinkLabel_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Proxy.
        /// </summary>
        internal static string SettingsForm_systemproxy_Text {
            get {
                return ResourceManager.GetString("SettingsForm_systemproxy_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlook.
        /// </summary>
        internal static string SettingsForm_tbSyncProfile_Text {
            get {
                return ResourceManager.GetString("SettingsForm_tbSyncProfile_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string SettingsForm_tbtnAdvanced_Text {
            get {
                return ResourceManager.GetString("SettingsForm_tbtnAdvanced_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string SettingsForm_tbtnGeneral_Text {
            get {
                return ResourceManager.GetString("SettingsForm_tbtnGeneral_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy.
        /// </summary>
        internal static string SettingsForm_tbtnProxy_Text {
            get {
                return ResourceManager.GetString("SettingsForm_tbtnProxy_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GooOut - Multisynchronizer.
        /// </summary>
        internal static string SettingsForm_Text {
            get {
                return ResourceManager.GetString("SettingsForm_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        internal static string SettingsForm_toolStripMenuItem2_Text {
            get {
                return ResourceManager.GetString("SettingsForm_toolStripMenuItem2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string SettingsForm_toolStripMenuItem5_Text {
            get {
                return ResourceManager.GetString("SettingsForm_toolStripMenuItem5_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toolStrip1.
        /// </summary>
        internal static string SettingsForm_TsTabs_Text {
            get {
                return ResourceManager.GetString("SettingsForm_TsTabs_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Sync {
            get {
                object obj = ResourceManager.GetObject("Sync", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Sync1 {
            get {
                object obj = ResourceManager.GetObject("Sync1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Sync2 {
            get {
                object obj = ResourceManager.GetObject("Sync2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string TrialityNotifierForm_btnClose_Text {
            get {
                return ResourceManager.GetString("TrialityNotifierForm_btnClose_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is trial version. Please register.
        /// </summary>
        internal static string TrialityNotifierForm_Text {
            get {
                return ResourceManager.GetString("TrialityNotifierForm_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The trial version is expired. Following functionalities are not available:
        ///Calendar synchronization
        ///
        ///In order to get full functionality you should register your copy.
        /// </summary>
        internal static string Warning_ApplicationExpired {
            get {
                return ResourceManager.GetString("Warning_ApplicationExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The saved folder is not found in selected profile. Default folder will be used instead..
        /// </summary>
        internal static string Warning_SavedFolderIdNotFound {
            get {
                return ResourceManager.GetString("Warning_SavedFolderIdNotFound", resourceCulture);
            }
        }
    }
}
