//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R.GoogleOutlookSync.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Software\\Rasoft\\GoogleOutlookSync")]
        public string ApplicationRegistryKey {
            get {
                return ((string)(this["ApplicationRegistryKey"]));
            }
            set {
                this["ApplicationRegistryKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CalendarDaysBefore")]
        public string CalendarSettings_RangeBefore {
            get {
                return ((string)(this["CalendarSettings_RangeBefore"]));
            }
            set {
                this["CalendarSettings_RangeBefore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CalendarDaysAfter")]
        public string CalendarSettings_RangeAfter {
            get {
                return ((string)(this["CalendarSettings_RangeAfter"]));
            }
            set {
                this["CalendarSettings_RangeAfter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CalendarName")]
        public string CalendarSettings_CalendarName {
            get {
                return ((string)(this["CalendarSettings_CalendarName"]));
            }
            set {
                this["CalendarSettings_CalendarName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("primary")]
        public string GoogleUrl_Calendar {
            get {
                return ((string)(this["GoogleUrl_Calendar"]));
            }
            set {
                this["GoogleUrl_Calendar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GoogleItemID")]
        public string ExtendedPropertyName_GoogleIDInOutlookItem {
            get {
                return ((string)(this["ExtendedPropertyName_GoogleIDInOutlookItem"]));
            }
            set {
                this["ExtendedPropertyName_GoogleIDInOutlookItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("StartDay")]
        public string RegistrationSettings_ExpirationDate {
            get {
                return ((string)(this["RegistrationSettings_ExpirationDate"]));
            }
            set {
                this["RegistrationSettings_ExpirationDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Identity")]
        public string RegistrationSettings_RegistrationNumberKey {
            get {
                return ((string)(this["RegistrationSettings_RegistrationNumberKey"]));
            }
            set {
                this["RegistrationSettings_RegistrationNumberKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int RegistrationSettings_TrialityDuration {
            get {
                return ((int)(this["RegistrationSettings_TrialityDuration"]));
            }
            set {
                this["RegistrationSettings_TrialityDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.gooout.net/help.html")]
        public string URL_Help {
            get {
                return ((string)(this["URL_Help"]));
            }
            set {
                this["URL_Help"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.gooout.net/terms-of-service.html")]
        public string URL_Terms {
            get {
                return ((string)(this["URL_Terms"]));
            }
            set {
                this["URL_Terms"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.gooout.net")]
        public string URL_Register {
            get {
                return ((string)(this["URL_Register"]));
            }
            set {
                this["URL_Register"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsNotRegistered {
            get {
                return ((bool)(this["IsNotRegistered"]));
            }
            set {
                this["IsNotRegistered"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.gooout.net/download/")]
        public string URL_Update {
            get {
                return ((string)(this["URL_Update"]));
            }
            set {
                this["URL_Update"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.gooout.net/popup/popup.php")]
        public global::System.Uri URL_TrialityNotifier {
            get {
                return ((global::System.Uri)(this["URL_TrialityNotifier"]));
            }
            set {
                this["URL_TrialityNotifier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("InstallTime")]
        public string Registry_InstallTimeValue {
            get {
                return ((string)(this["Registry_InstallTimeValue"]));
            }
            set {
                this["Registry_InstallTimeValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.gooout.net/statistics.php")]
        public global::System.Uri URL_InstallNotification {
            get {
                return ((global::System.Uri)(this["URL_InstallNotification"]));
            }
            set {
                this["URL_InstallNotification"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Software\\Microsoft\\Windows\\CurrentVersion\\RunOnce")]
        public string Registry_Key_Autorun {
            get {
                return ((string)(this["Registry_Key_Autorun"]));
            }
            set {
                this["Registry_Key_Autorun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int AttemptsAmount {
            get {
                return ((int)(this["AttemptsAmount"]));
            }
            set {
                this["AttemptsAmount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Software\\Microsoft\\Office\\16.0\\Outlook\\Profiles")]
        public string Registry_Key_OutlookProfiles {
            get {
                return ((string)(this["Registry_Key_OutlookProfiles"]));
            }
            set {
                this["Registry_Key_OutlookProfiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DefaultProfile")]
        public string Registry_Value_OutlookDefaultProfile {
            get {
                return ((string)(this["Registry_Value_OutlookDefaultProfile"]));
            }
            set {
                this["Registry_Value_OutlookDefaultProfile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-2147023174")]
        public int Constant_RPC_server_is_not_available {
            get {
                return ((int)(this["Constant_RPC_server_is_not_available"]));
            }
            set {
                this["Constant_RPC_server_is_not_available"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-2147352567")]
        public int Constant_Profile_is_not_set_up {
            get {
                return ((int)(this["Constant_Profile_is_not_set_up"]));
            }
            set {
                this["Constant_Profile_is_not_set_up"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-2147220991")]
        public int Constant_ID_not_found {
            get {
                return ((int)(this["Constant_ID_not_found"]));
            }
            set {
                this["Constant_ID_not_found"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("27900843233-1ujfh188ra7ng3dm3h0bbdlgiuhklovg.apps.googleusercontent.com")]
        public string GoogleAuth_ClientID {
            get {
                return ((string)(this["GoogleAuth_ClientID"]));
            }
            set {
                this["GoogleAuth_ClientID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BlhKyuT59ppUidfoYHiWBl1G")]
        public string GoogleAuth_ClientSecret {
            get {
                return ((string)(this["GoogleAuth_ClientSecret"]));
            }
            set {
                this["GoogleAuth_ClientSecret"] = value;
            }
        }
    }
}
